# Generated by Django 4.2.8 on 2023-12-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dec',
            new_name='desc',
        ),
    ]
